### ISSUE TITLE
Windows only

### ISSUE THREAD

**Issue by L3o-pold** [fakoua/deno_shot#2]
Could be nice to add it in your README... 

https://github.com/fakoua/deno_shot/blob/b69afb8e3ef704a3cf3abd8bcb0b983aa3d34f29/src/utils.ts#L11

**Comment by fakoua** [comment]
I'm so sorry, it was missing in the documentation.
Will fix it.

**Comment by m-thomson** [comment]
It still says nothing in the readme about this being windows only.
